version: "3"

services:
  db:
    image: postgres:11-alpine
    container_name: pg-nest-boilerplate
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-nest-boilerplate}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-secret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
