version: "3"

services:
  db:
    image: postgres:11-alpine
    container_name: nest-boilerplate-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-nest_boilerplate}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-secret}
    volumes:
      - pg_data:/home/app/nest_boilerplate/data
volumes:
  pg_data:
